### ISSUE TITLE
Order里的OrderID是如何确定的

### ISSUE THREAD

**Issue by leedstyh** [z-Wind/gotd#1]
请教下，比如说PlaceOrder里的Order，OrderID是如何确定的，是自己指定的吗，还是发送一个Order，服务器返回一个ID

**Comment by z-Wind** [comment]
OrderID 是建立 order 時，TD 決定的
PlaceOrder 成功，並不會回傳 OrderID
要用以下兩個方法得到 OrderID
GetOrdersByQuery
GetOrdersByPath

詳細用法，可參考
https://github.com/z-Wind/gotd/blob/master/orders_test.go
TD API
https://developer.tdameritrade.com/account-access/apis

**Comment by leedstyh** [comment]
谢谢，那就是说我place了一个Order，无法知道Order的执行情况，还得再发送一个请求才能知道？

那再请教下，假如说我做个app，两个人使用这个app，连接同一个TD账号，那我该如何区分Order是哪个人发出的呢？
